### PR TITLE
Added Ableton Push 2

### PR DESCRIPTION
**Pull request by Vaynerix**
Hi Sema.
While adding this, I cleaned up the list a bit for better oversight.
Removed a space right after the f7 of Roland XV-3080.
Akai Push 1 gives a reply too, but it contains a unique device serial. I changed the serial to 12345-12345678 for this example.   
f0 7e 00 06 02 47 15 00 19 00 01 01 06 00 00 00 00 00 31 32 33 34 35 2d 31 32 33 34 35 36 37 38 00 00 f7

Thanks for sharing this project!

- Bjorn

### CODE REVIEW

**Comment by jazz-soft** [comment]
Hi Bjorn,

Thank you for contributing!

You should not rearrange the lines: they are sorted by ID sequence, not by brand name because one manufacturer may produce multiple brands, e.g. Roland/BOSS.
Could you please fix your commit?

Does the script identify Akai Push correctly? - It should use only the beginning of the response string and ignore the end.

Thank you!

**Comment by Vaynerix** [comment]
Ah, and following that logic I think Ableton Push 2 should be way at the end of the list then.
So only one line to add instead of switching up 50 others.
My bad, sunday cleaning got a bit out of hand!

I'll get back to you tomorrow to verify that the Akai Push is properly detected. Away from the studio at the moment.

Kind Regards,

Bjorn

**Comment by Vaynerix** [comment]
Hi Sema,

I updated the file as generated from the grunt process. And I can confirm that the Akai Push is properly identified.
My apologies for the messiness of this addition. While I've learned a lot from the online documentation, I'm learning even more from your readme files.
Thanks for all the documentation!

Cheers,

Bjorn

**Comment by jazz-soft** [comment]
I have published the new release at npm.
Please check if your instruments are recognized correctly.
Thanks a lot!

**Comment by Vaynerix** [comment]
Cool! I checked the new release and both devices are recognized correctly. Very useful, since the MIDI Port names are different on OSX vs. Windows.
I suppose I can delete this branch now, but wasn't sure if I could comment back after doing so.

Cheers,
Bjorn

**Comment by jazz-soft** [comment]
Don't forget to come back when you when you get some new devices ;)

**Pull request merged**
